variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      password_hash: #{yescrypt}
      ssh_authorized_keys:
        - #{ssh_identity} 
      groups:
        - docker
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: |
          #{hostname}
    - path: /etc/NetworkManager/system-connections/#{interface}.nmconnection
      mode: 0600
      contents:
        inline: |
          [connection]
          id=#{interface}
          type=ethernet
          autoconnect=true
          interface-name=#{interface}
          [ipv4]
          address1=#{ip}/#{prefix},#{gateway}
          dhcp-hostname=#{hostname}
          dns=8.8.8.8;
          dns-search=
          method=manual
    - path: /etc/docker/daemon.json
      mode: 0644
      contents:
        inline: |
          {
            "insecure-registries" : ["#{registry_ip}:5000"]
          }
