version: '3.8'

services:
#  web:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    container_name: flaskapi
#    ports:
#      - "5000:5000"
#    environment:
#      - CONFIG=testing
#      - POSTGRES_DB=your_db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=temppassword
#      - DATABASE_URI=postgresql://postgres:temppassword@db:5432/your_db
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - ./api:/app
#    command: python3 app.py

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=your_db
      - POSTGRES_USER=postgres  # Root user
      - POSTGRES_PASSWORD=temppassword  # Strong password for root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Health check with root user
      interval: 10s
      timeout: 5s
      retries: 5

#  test:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    container_name: flaskapi_test
#    environment:
#      - PYTHONPATH=/app/src
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - ./api:/app
#    command: pytest

volumes:
  postgres_data:
